// 1 - Array

const lista = [1 , 2, 3, 4, 5];

console.log(lista)

console.log(typeof lista)

const itens = ["Pedro", true, 2, 3.12, [], {}]

console.log(itens)

// 2 - Mais sobre arrays
const arr = ["a", "b", "c", "d", "e"]

console.log(arr[0])

console.log(arr[78])

console.log(arr[2])

// 3 - propriedades

const numbers= [5, 3, 2];

console.log(numbers.length);

console.log(numbers["length"]);

const myName = "Pedro"

console.log(myName.length)